language: go

go:
    - 1.13.x
    - 1.11.x

before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.23.1

script:
    - golangci-lint run       # run a bunch of code checkers/linters in parallel
    - go test -cover -v -race ./...  # Run all the tests with the race detector enabled
