language: go

go:
    - 1.1x

script:
    - golangci-lint run       # run a bunch of code checkers/linters in parallel
    - go test -cover -v -race ./...  # Run all the tests with the race detector enabled
